<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="iTextSharp" />
    <!-- iTextSharp 5.5.13.6 references this assembly but omits it from its NuGet dependencies. -->
    <PackageReference Include="itext.commons" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <EmbeddedResource Include="Documents/Fonts/DejaVuSansMono.ttf" />
    <None Update="Documents/Fonts/LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
