// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwiftReview.Infrastructure.Persistence;

#nullable disable

namespace SwiftReview.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SwiftReviewDbContext))]
    [Migration("20260903180506_MoveApplicationTablesToOrp")]
    partial class MoveApplicationTablesToOrp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ORP")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwiftReview.Domain.Assignments.Assignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AssignedBy")
                        .HasColumnType("int");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[EndedAt] IS NULL");

                    b.ToTable("Assignments", "ORP");
                });

            modelBuilder.Entity("SwiftReview.Domain.Auditing.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewState")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OldState")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "Timestamp");

                    b.ToTable("AuditEvents", "ORP");
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Branches", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "London"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dublin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Singapore"
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Departments", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TFO"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DC"
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "message.view"
                        },
                        new
                        {
                            Id = 2,
                            Name = "message.assign"
                        },
                        new
                        {
                            Id = 3,
                            Name = "review.level1"
                        },
                        new
                        {
                            Id = 4,
                            Name = "review.level2"
                        },
                        new
                        {
                            Id = 5,
                            Name = "review.level3"
                        },
                        new
                        {
                            Id = 6,
                            Name = "review.reject"
                        },
                        new
                        {
                            Id = 7,
                            Name = "review.undo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "audit.view"
                        },
                        new
                        {
                            Id = 9,
                            Name = "workflow.manage"
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CS Reviewer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "TFO Reviewer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DC Reviewer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DC Senior Reviewer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", "ORP");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 9
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "CS Reviewer",
                            UserName = "cs-reviewer"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "TFO Reviewer",
                            UserName = "tfo-reviewer"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "DC Reviewer",
                            UserName = "dc-reviewer"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "DC Senior Reviewer",
                            UserName = "dc-senior"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Supervisor",
                            UserName = "supervisor"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Administrator",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.UserBranch", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("UserBranches", "ORP");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BranchId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BranchId = 2
                        },
                        new
                        {
                            UserId = 3,
                            BranchId = 3
                        },
                        new
                        {
                            UserId = 4,
                            BranchId = 1
                        },
                        new
                        {
                            UserId = 4,
                            BranchId = 2
                        },
                        new
                        {
                            UserId = 4,
                            BranchId = 3
                        },
                        new
                        {
                            UserId = 5,
                            BranchId = 1
                        },
                        new
                        {
                            UserId = 5,
                            BranchId = 2
                        },
                        new
                        {
                            UserId = 5,
                            BranchId = 3
                        },
                        new
                        {
                            UserId = 6,
                            BranchId = 1
                        },
                        new
                        {
                            UserId = 6,
                            BranchId = 2
                        },
                        new
                        {
                            UserId = 6,
                            BranchId = 3
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.UserDepartment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("UserDepartments", "ORP");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DepartmentId = 1
                        },
                        new
                        {
                            UserId = 2,
                            DepartmentId = 2
                        },
                        new
                        {
                            UserId = 3,
                            DepartmentId = 3
                        },
                        new
                        {
                            UserId = 4,
                            DepartmentId = 1
                        },
                        new
                        {
                            UserId = 4,
                            DepartmentId = 2
                        },
                        new
                        {
                            UserId = 4,
                            DepartmentId = 3
                        },
                        new
                        {
                            UserId = 5,
                            DepartmentId = 1
                        },
                        new
                        {
                            UserId = 5,
                            DepartmentId = 2
                        },
                        new
                        {
                            UserId = 5,
                            DepartmentId = 3
                        },
                        new
                        {
                            UserId = 6,
                            DepartmentId = 1
                        },
                        new
                        {
                            UserId = 6,
                            DepartmentId = 2
                        },
                        new
                        {
                            UserId = 6,
                            DepartmentId = 3
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "ORP");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Messages.Message", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageId");

                    b.Property<int?>("CurrentAssigneeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("WorkflowDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssigneeId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("Messages", "ORP");
                });

            modelBuilder.Entity("SwiftReview.Domain.Reviews.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("MessageId", "Level")
                        .IsUnique()
                        .HasFilter("[Status] <> N'Undone'");

                    b.ToTable("Reviews", "ORP");
                });

            modelBuilder.Entity("SwiftReview.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MessageType", "DepartmentId", "BranchId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("WorkflowDefinitions", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            IsActive = true,
                            MessageType = "MT199",
                            Name = "Single Review"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            IsActive = true,
                            MessageType = "MT299",
                            Name = "Two Reviews"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            IsActive = true,
                            MessageType = "MT671",
                            Name = "Three Reviews"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            IsActive = true,
                            MessageType = "MT700",
                            Name = "MT700 Single Review"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            IsActive = true,
                            MessageType = "MT710",
                            Name = "MT710 Two Reviews"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            IsActive = true,
                            MessageType = "MT760",
                            Name = "MT760 Three Reviews"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            IsActive = true,
                            MessageType = "MT799",
                            Name = "MT799 Single Review"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            IsActive = true,
                            MessageType = "MT999",
                            Name = "MT999 Two Reviews"
                        });
                });

            modelBuilder.Entity("SwiftReview.Domain.Workflows.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewLevel")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowDefinitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Order")
                        .IsUnique();

                    b.ToTable("WorkflowSteps", "ORP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Order = 2,
                            Required = true,
                            ReviewLevel = 2,
                            WorkflowDefinitionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 3
                        },
                        new
                        {
                            Id = 5,
                            Order = 2,
                            Required = true,
                            ReviewLevel = 2,
                            WorkflowDefinitionId = 3
                        },
                        new
                        {
                            Id = 6,
                            Order = 3,
                            Required = true,
                            ReviewLevel = 3,
                            WorkflowDefinitionId = 3
                        },
                        new
                        {
                            Id = 7,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 4
                        },
                        new
                        {
                            Id = 8,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 5
                        },
                        new
                        {
                            Id = 9,
                            Order = 2,
                            Required = true,
                            ReviewLevel = 2,
                            WorkflowDefinitionId = 5
                        },
                        new
                        {
                            Id = 10,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 6
                        },
                        new
                        {
                            Id = 11,
                            Order = 2,
                            Required = true,
                            ReviewLevel = 2,
                            WorkflowDefinitionId = 6
                        },
                        new
                        {
                            Id = 12,
                            Order = 3,
                            Required = true,
                            ReviewLevel = 3,
                            WorkflowDefinitionId = 6
                        },
                        new
                        {
                            Id = 13,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 7
                        },
                        new
                        {
                            Id = 14,
                            Order = 1,
                            Required = true,
                            ReviewLevel = 1,
                            WorkflowDefinitionId = 8
                        },
                        new
                        {
                            Id = 15,
                            Order = 2,
                            Required = true,
                            ReviewLevel = 2,
                            WorkflowDefinitionId = 8
                        });
                });

            modelBuilder.Entity("SwiftReview.Infrastructure.Persistence.SwiftMessageRecord", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    b.Property<string>("Account")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MessageId");

                    b.ToTable((string)null);

                    b.ToView("SwiftMessageSource", "ORP");
                });

            modelBuilder.Entity("SwiftReview.Domain.Assignments.Assignment", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Messages.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Auditing.AuditEvent", b =>
                {
                    b.HasOne("SwiftReview.Domain.Messages.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Message");
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.UserBranch", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany("Branches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.UserDepartment", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany("Departments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SwiftReview.Domain.Messages.Message", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CurrentAssigneeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SwiftReview.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Reviews.Review", b =>
                {
                    b.HasOne("SwiftReview.Domain.Messages.Message", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SwiftReview.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.HasOne("SwiftReview.Domain.Identity.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SwiftReview.Domain.Identity.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Workflows.WorkflowStep", b =>
                {
                    b.HasOne("SwiftReview.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("SwiftReview.Domain.Identity.User", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Departments");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SwiftReview.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
