-- Run the entire script in SSMS against the target TEST database after applying migrations.
-- DESTRUCTIVE: every run replaces all ORP application data, including users and audit history.
-- Stop the application and other writers before running. Schema and migration history are preserved.
-- All IDs are generated by SQL Server. No database/schema creation or migration is performed.
SET NOCOUNT ON;
SET XACT_ABORT ON;
-- Required when writing tables with filtered indexes, including through sqlcmd.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

IF OBJECT_ID(N'orp.AuditEvents', N'U') IS NULL
    THROW 51000, 'Apply ORP migrations before loading test data.', 1;
IF @@TRANCOUNT <> 0
    THROW 51000, 'Run this script outside an existing transaction.', 1;

BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @lockResult int;
    EXEC @lockResult = sys.sp_getapplock @Resource=N'orp-swift-sync',
        @LockMode=N'Exclusive', @LockOwner=N'Transaction', @LockTimeout=0;
    IF @lockResult < 0 THROW 51000, 'Another ORP data writer is active.', 1;

    -- Delete dependent rows first; cleanup and loading roll back together on any failure.
    DELETE FROM [orp].[AuditEvents];
    DELETE FROM [orp].[AccessAuditEvents];
    DELETE FROM [orp].[Reviews];
    DELETE FROM [orp].[Assignments];
    DELETE FROM [orp].[Messages];
    DELETE FROM [orp].[SwiftMessages];
    DELETE FROM [orp].[WorkflowSteps];
    DELETE FROM [orp].[WorkflowDefinitions];
    DELETE FROM [orp].[UserRoles];
    DELETE FROM [orp].[RolePermissions];
    DELETE FROM [orp].[Users];
    DELETE FROM [orp].[Roles];
    DELETE FROM [orp].[Permissions];
    DELETE FROM [orp].[Branches];
    DELETE FROM [orp].[Departments];

    INSERT INTO [orp].[Branches] ([Name]) VALUES (N'London'),(N'Dublin'),(N'Singapore');
    INSERT INTO [orp].[Departments] ([Name]) VALUES (N'CS'),(N'TFO'),(N'DC');

    INSERT INTO [orp].[Permissions] ([Name]) VALUES
        (N'message.view'),(N'message.assign'),(N'review.level1'),(N'review.level2'),
        (N'review.level3'),(N'review.undo'),(N'audit.view'),(N'workflow.manage');

    INSERT INTO [orp].[Roles] ([Name]) VALUES (N'Reviewer'),(N'Operations manager');

    INSERT INTO [orp].[RolePermissions] ([RoleId],[PermissionId])
    SELECT r.[Id],p.[Id] FROM [orp].[Roles] r CROSS JOIN [orp].[Permissions] p
    WHERE r.[Name]=N'Operations manager'
        OR (r.[Name]=N'Reviewer'
            AND p.[Name] IN (N'message.view',N'message.assign',N'review.level1',
                N'review.level2',N'review.level3',N'audit.view'));

    DECLARE @users TABLE ([UserName] nvarchar(80),[DisplayName] nvarchar(160),
        [RoleName] nvarchar(80),[IsAdmin] bit,[AllScopes] bit);
    -- Three broadly scoped reviewers support every workflow; Amelia demonstrates scoped access.
    INSERT INTO @users VALUES
        (N'amelia.hart',N'Amelia Hart',N'Reviewer',0,0),
        (N'theo.mercer',N'Theo Mercer',N'Reviewer',0,1),
        (N'priya.nair',N'Priya Nair',N'Reviewer',0,1),
        (N'lucas.bennett',N'Lucas Bennett',N'Reviewer',0,1),
        (N'admin',N'Administrator',N'Operations manager',1,1);

    INSERT INTO [orp].[Users] ([UserName],[DisplayName],[IsGlobalAdministrator])
    SELECT [UserName],[DisplayName],[IsAdmin] FROM @users;

    INSERT INTO [orp].[UserRoles] ([UserId],[BranchId],[DepartmentId],[RoleId])
    SELECT u.[Id],b.[Id],d.[Id],r.[Id] FROM @users v
    JOIN [orp].[Users] u ON u.[UserName]=v.[UserName]
    JOIN [orp].[Roles] r ON r.[Name]=v.[RoleName]
    CROSS JOIN [orp].[Branches] b
    CROSS JOIN [orp].[Departments] d
    WHERE v.[AllScopes]=1 OR (b.[Name]=N'London' AND d.[Name]=N'CS');

    DECLARE @workflows TABLE ([Ordinal] int,[MessageType] nvarchar(20),[Name] nvarchar(100),
        [DepartmentName] nvarchar(80),[Levels] int);
    INSERT INTO @workflows VALUES
        (0,N'MT199',N'1 reviewer',N'CS',1),
        (1,N'MT299',N'1,2 reviewers',N'TFO',2),
        (2,N'MT671',N'1,2,3 reviewers',N'DC',3);
    INSERT INTO [orp].[WorkflowDefinitions] ([Name],[MessageType],[DepartmentId],[BranchId],[IsActive])
    SELECT v.[Name],v.[MessageType],d.[Id],NULL,1 FROM @workflows v
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName];
    INSERT INTO [orp].[WorkflowSteps] ([WorkflowDefinitionId],[Order],[ReviewLevel],[Required])
    SELECT w.[Id],level.[Value],level.[Value],1 FROM @workflows v
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=v.[MessageType]
    JOIN (VALUES (1),(2),(3)) level([Value]) ON level.[Value]<=v.[Levels];

    DECLARE @now datetimeoffset = SYSUTCDATETIME();
    ;WITH numbers AS (SELECT 1 AS n UNION ALL SELECT n+1 FROM numbers WHERE n<75)
    INSERT INTO [orp].[SwiftMessages]
        ([WarehouseId],[BodyContainsMx],[BodyContainsMt],[Body],[MessageType],[MessageTypeShort],
         [MessageLength],[MessageDate],[SenderRequestor],[ReceiverResponder],[Direction],
         [BranchId],[DepartmentId],[RoutingStatus],[LastSynchronizedAtUtc])
    SELECT CONCAT(N'TEST-',RIGHT(CONCAT(N'00000',n),5)),0,1,body.[Value],v.[MessageType],
        SUBSTRING(v.[MessageType],3,3),LEN(body.[Value]),DATEADD(hour,n,@now),
        N'TESTGB2LXXX',N'DEMOGB2LXXX',N'IN',b.[Id],d.[Id],N'Routed',@now
    FROM numbers
    JOIN @workflows v ON v.[Ordinal]=(n-1)%3
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName]
    JOIN [orp].[Branches] b ON b.[Name]=CASE ((n-1)/3+(n-1)%3)%3
        WHEN 0 THEN N'London' WHEN 1 THEN N'Dublin' ELSE N'Singapore' END
    CROSS APPLY (SELECT CONCAT(N'{1:F01TESTGB2LXXXX0000000000}{2:I',
        SUBSTRING(v.[MessageType],3,3),N'DEMOGB2LXXXXN}{4:',CHAR(10),N':20:TEST-',n,
        CHAR(10),N':79:SYNTHETIC TEST MESSAGE',CHAR(10),N'-}')) body([Value]);

    INSERT INTO [orp].[Messages] ([MessageId],[State],[CurrentAssigneeId],[WorkflowDefinitionId])
    SELECT s.[MessageId],N'New',NULL,w.[Id] FROM [orp].[SwiftMessages] s
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=s.[MessageType]
        AND w.[DepartmentId]=s.[DepartmentId] AND w.[IsActive]=1 AND w.[BranchId] IS NULL;

    INSERT INTO [orp].[AuditEvents]
        ([MessageId],[EventType],[UserId],[Timestamp],[OldState],[NewState],[DetailsJson],[CorrelationId],[ReviewId])
    SELECT [MessageId],N'MessageRegistered',NULL,@now,NULL,N'New',
        CONCAT(N'{"workflowDefinitionId":',[WorkflowDefinitionId],N'}'),N'sql-test-seed-v2',NULL
    FROM [orp].[Messages];

    COMMIT;
    PRINT 'Loaded 5 users, 3 workflows and 75 messages into orp.';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK;
    THROW;
END CATCH;
