-- Run the entire script in SSMS against the target TEST database after applying migrations.
-- Only a fresh orp schema is accepted (migration-created roles/permissions are allowed).
-- All IDs are generated by SQL Server. No database/schema creation or migration is performed.
SET NOCOUNT ON;
SET XACT_ABORT ON;
-- Required when writing tables with filtered indexes, including through sqlcmd.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

IF OBJECT_ID(N'orp.AuditEvents', N'U') IS NULL
    THROW 51000, 'Apply ORP migrations before loading test data.', 1;
IF @@TRANCOUNT <> 0
    THROW 51000, 'Run this script outside an existing transaction.', 1;

BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @lockResult int;
    EXEC @lockResult = sys.sp_getapplock @Resource=N'orp-swift-sync',
        @LockMode=N'Exclusive', @LockOwner=N'Transaction', @LockTimeout=0;
    IF @lockResult < 0 THROW 51000, 'Another ORP data writer is active.', 1;

    IF EXISTS (SELECT 1 FROM [orp].[AuditEvents] WHERE [CorrelationId]=N'sql-test-seed-v1')
    BEGIN
        COMMIT;
        PRINT 'Test data already loaded; nothing changed.';
        RETURN;
    END;

    IF EXISTS (SELECT 1 FROM [orp].[Users])
       OR EXISTS (SELECT 1 FROM [orp].[Branches])
       OR EXISTS (SELECT 1 FROM [orp].[Departments])
       OR EXISTS (SELECT 1 FROM [orp].[WorkflowDefinitions])
       OR EXISTS (SELECT 1 FROM [orp].[SwiftMessages])
       OR EXISTS (SELECT 1 FROM [orp].[Messages])
       OR EXISTS (SELECT 1 FROM [orp].[AuditEvents])
        THROW 51000, 'Test data requires a fresh ORP schema. Existing application data was found.', 1;

    INSERT INTO [orp].[Branches] ([Name]) VALUES (N'London'),(N'Dublin'),(N'Singapore');
    INSERT INTO [orp].[Departments] ([Name]) VALUES (N'CS'),(N'TFO'),(N'DC');

    INSERT INTO [orp].[Permissions] ([Name])
    SELECT v.[Name] FROM (VALUES
        (N'message.view'),(N'message.assign'),(N'review.level1'),(N'review.level2'),
        (N'review.level3'),(N'review.undo'),(N'audit.view'),(N'workflow.manage')) v([Name])
    WHERE NOT EXISTS (SELECT 1 FROM [orp].[Permissions] p WHERE p.[Name]=v.[Name]);

    INSERT INTO [orp].[Roles] ([Name])
    SELECT v.[Name] FROM (VALUES (N'CS Reviewer'),(N'TFO Reviewer'),(N'DC Reviewer'),
        (N'DC Senior Reviewer'),(N'Operations manager')) v([Name])
    WHERE NOT EXISTS (SELECT 1 FROM [orp].[Roles] r WHERE r.[Name]=v.[Name]);

    INSERT INTO [orp].[RolePermissions] ([RoleId],[PermissionId])
    SELECT r.[Id],p.[Id] FROM [orp].[Roles] r CROSS JOIN [orp].[Permissions] p
    WHERE (r.[Name]=N'Operations manager'
        OR (r.[Name] IN (N'CS Reviewer',N'DC Reviewer')
            AND p.[Name] IN (N'message.view',N'review.level1',N'audit.view'))
        OR (r.[Name]=N'TFO Reviewer'
            AND p.[Name] IN (N'message.view',N'review.level1',N'review.level2',N'audit.view'))
        OR (r.[Name]=N'DC Senior Reviewer'
            AND p.[Name] IN (N'message.view',N'review.level2',N'review.level3',N'review.undo',N'audit.view')))
      AND NOT EXISTS (SELECT 1 FROM [orp].[RolePermissions] g
          WHERE g.[RoleId]=r.[Id] AND g.[PermissionId]=p.[Id]);

    DECLARE @users TABLE ([UserName] nvarchar(80),[DisplayName] nvarchar(160),
        [RoleName] nvarchar(80),[BranchName] nvarchar(80),[DepartmentName] nvarchar(80),[IsAdmin] bit);
    -- NULL branch/department means access to all branches/departments.
    INSERT INTO @users VALUES
        (N'amelia.hart',N'Amelia Hart',N'CS Reviewer',N'London',N'CS',0),
        (N'theo.mercer',N'Theo Mercer',N'TFO Reviewer',N'Dublin',N'TFO',0),
        (N'priya.nair',N'Priya Nair',N'DC Reviewer',N'Singapore',N'DC',0),
        (N'victor.stone',N'Victor Stone',N'DC Senior Reviewer',NULL,N'DC',0),
        (N'admin',N'Administrator',N'Operations manager',NULL,NULL,1),
        (N'lucas.bennett',N'Lucas Bennett',N'CS Reviewer',N'Dublin',N'CS',0),
        (N'sofia.lindberg',N'Sofia Lindberg',N'CS Reviewer',N'Singapore',N'CS',0),
        (N'kenji.mori',N'Kenji Mori',N'TFO Reviewer',N'London',N'TFO',0),
        (N'nadia.kowalska',N'Nadia Kowalska',N'TFO Reviewer',N'Singapore',N'TFO',0),
        (N'mateo.silva',N'Mateo Silva',N'DC Reviewer',N'London',N'DC',0),
        (N'elena.petrova',N'Elena Petrova',N'DC Reviewer',N'Dublin',N'DC',0);
    INSERT INTO [orp].[Users] ([UserName],[DisplayName],[IsGlobalAdministrator])
    SELECT [UserName],[DisplayName],[IsAdmin] FROM @users;

    INSERT INTO [orp].[UserRoles] ([UserId],[BranchId],[DepartmentId],[RoleId])
    SELECT u.[Id],b.[Id],d.[Id],r.[Id] FROM @users v
    JOIN [orp].[Users] u ON u.[UserName]=v.[UserName]
    JOIN [orp].[Roles] r ON r.[Name]=v.[RoleName]
    JOIN [orp].[Branches] b ON v.[BranchName] IS NULL OR b.[Name]=v.[BranchName]
    JOIN [orp].[Departments] d ON v.[DepartmentName] IS NULL OR d.[Name]=v.[DepartmentName];

    DECLARE @workflows TABLE ([Ordinal] int,[MessageType] nvarchar(20),[Name] nvarchar(100),
        [DepartmentName] nvarchar(80),[Levels] int);
    INSERT INTO @workflows VALUES
        (0,N'MT199',N'Single Review',N'CS',1),
        (1,N'MT299',N'Two Reviews',N'TFO',2),
        (2,N'MT671',N'Three Reviews',N'DC',3),
        (3,N'MT700',N'MT700 Single Review',N'CS',1),
        (4,N'MT710',N'MT710 Two Reviews',N'TFO',2),
        (5,N'MT760',N'MT760 Three Reviews',N'DC',3),
        (6,N'MT799',N'MT799 Single Review',N'CS',1),
        (7,N'MT999',N'MT999 Two Reviews',N'TFO',2);
    INSERT INTO [orp].[WorkflowDefinitions] ([Name],[MessageType],[DepartmentId],[BranchId],[IsActive])
    SELECT v.[Name],v.[MessageType],d.[Id],NULL,1 FROM @workflows v
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName];
    INSERT INTO [orp].[WorkflowSteps] ([WorkflowDefinitionId],[Order],[ReviewLevel],[Required])
    SELECT w.[Id],level.[Value],level.[Value],1 FROM @workflows v
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=v.[MessageType]
    JOIN (VALUES (1),(2),(3)) level([Value]) ON level.[Value]<=v.[Levels];

    DECLARE @now datetimeoffset = SYSUTCDATETIME();
    ;WITH numbers AS (SELECT 1 AS n UNION ALL SELECT n+1 FROM numbers WHERE n<75)
    INSERT INTO [orp].[SwiftMessages]
        ([WarehouseId],[BodyContainsMx],[BodyContainsMt],[Body],[MessageType],[MessageTypeShort],
         [MessageLength],[MessageDate],[SenderRequestor],[ReceiverResponder],[Direction],
         [BranchId],[DepartmentId],[RoutingStatus],[LastSynchronizedAtUtc])
    SELECT CONCAT(N'TEST-',RIGHT(CONCAT(N'00000',n),5)),0,1,body.[Value],v.[MessageType],
        SUBSTRING(v.[MessageType],3,3),LEN(body.[Value]),DATEADD(hour,n,@now),
        N'TESTGB2LXXX',N'DEMOGB2LXXX',N'IN',b.[Id],d.[Id],N'Routed',@now
    FROM numbers
    JOIN @workflows v ON v.[Ordinal]=(n-1)%8
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName]
    JOIN [orp].[Branches] b ON b.[Name]=CASE (n-1)%3
        WHEN 0 THEN N'London' WHEN 1 THEN N'Dublin' ELSE N'Singapore' END
    CROSS APPLY (SELECT CONCAT(N'{1:F01TESTGB2LXXXX0000000000}{2:I',
        SUBSTRING(v.[MessageType],3,3),N'DEMOGB2LXXXXN}{4:',CHAR(10),N':20:TEST-',n,
        CHAR(10),N':79:SYNTHETIC TEST MESSAGE',CHAR(10),N'-}')) body([Value]);

    INSERT INTO [orp].[Messages] ([MessageId],[State],[CurrentAssigneeId],[WorkflowDefinitionId])
    SELECT s.[MessageId],N'New',NULL,w.[Id] FROM [orp].[SwiftMessages] s
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=s.[MessageType]
        AND w.[DepartmentId]=s.[DepartmentId] AND w.[IsActive]=1 AND w.[BranchId] IS NULL;

    INSERT INTO [orp].[AuditEvents]
        ([MessageId],[EventType],[UserId],[Timestamp],[OldState],[NewState],[DetailsJson],[CorrelationId],[ReviewId])
    SELECT [MessageId],N'MessageRegistered',NULL,@now,NULL,N'New',
        CONCAT(N'{"workflowDefinitionId":',[WorkflowDefinitionId],N'}'),N'sql-test-seed-v1',NULL
    FROM [orp].[Messages];

    COMMIT;
    PRINT 'Loaded 11 users, 8 workflows and 75 messages into orp.';
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK;
    THROW;
END CATCH;
