-- Run the entire script in SSMS against the target TEST database after applying migrations.
-- DESTRUCTIVE: every run replaces all ORP application data, including users and audit history.
-- Stop the application and other writers before running. Schema and migration history are preserved.
-- All IDs are generated by SQL Server. No database/schema creation or migration is performed.
-- Demo scenarios (not a production routing matrix):
--   Incoming MT199 / CS:  one final confirmation; ordinary Undo is disabled.
--   Incoming MT299 / TFO: two confirmations; any authorised reviewer can undo the first,
--                also cancelling an active second review. The final approval is locked.
--   Incoming MT671 / DC:  three reviews; only the original reviewer can undo the latest approval,
--                including the final approval. Active reviews block Undo.
--   Outgoing MT299 / TFO: one final confirmation; ordinary Undo is disabled.
-- Global administrators retain their exception when no review is active.
-- All 100 messages start New. Use the application to assign, review and inspect the audit.
SET NOCOUNT ON;
SET XACT_ABORT ON;
-- Required when writing tables with filtered indexes, including through sqlcmd.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;

IF OBJECT_ID(N'orp.AuditEvents', N'U') IS NULL
    THROW 51000, 'Apply ORP migrations before loading test data.', 1;
IF COL_LENGTH(N'orp.WorkflowDefinitions', N'UndoApprovalMode') IS NULL
    OR COL_LENGTH(N'orp.WorkflowDefinitions', N'UndoActorMode') IS NULL
    OR COL_LENGTH(N'orp.WorkflowDefinitions', N'UndoActiveReviewMode') IS NULL
    THROW 51000, 'Apply AddWorkflowUndoPolicy before loading test data.', 1;
IF COL_LENGTH(N'orp.WorkflowDefinitions', N'Direction') IS NULL
    THROW 51000, 'Apply AddMessageDirection before loading test data.', 1;
IF @@TRANCOUNT <> 0
    THROW 51000, 'Run this script outside an existing transaction.', 1;

BEGIN TRY
    BEGIN TRANSACTION;
    DECLARE @lockResult int;
    EXEC @lockResult = sys.sp_getapplock @Resource=N'orp-swift-sync',
        @LockMode=N'Exclusive', @LockOwner=N'Transaction', @LockTimeout=0;
    IF @lockResult < 0 THROW 51000, 'Another ORP data writer is active.', 1;

    -- 1. Reset demo data. Cleanup and loading roll back together on any failure.
    -- Delete dependent rows first; preserve the schema and EF migration history.
    DELETE FROM [orp].[AuditEvents];
    DELETE FROM [orp].[AccessAuditEvents];
    DELETE FROM [orp].[Reviews];
    DELETE FROM [orp].[Assignments];
    DELETE FROM [orp].[Messages];
    DELETE FROM [orp].[SwiftMessages];
    DELETE FROM [orp].[WorkflowSteps];
    DELETE FROM [orp].[WorkflowDefinitions];
    DELETE FROM [orp].[UserRoles];
    DELETE FROM [orp].[RolePermissions];
    DELETE FROM [orp].[Users];
    DELETE FROM [orp].[Roles];
    DELETE FROM [orp].[Permissions];
    DELETE FROM [orp].[Branches];
    DELETE FROM [orp].[Departments];

    -- 2. Reference data and role permissions.
    INSERT INTO [orp].[Branches] ([Name]) VALUES (N'London'),(N'Dublin'),(N'Singapore');
    INSERT INTO [orp].[Departments] ([Name]) VALUES (N'CS'),(N'TFO'),(N'DC');

    INSERT INTO [orp].[Permissions] ([Name]) VALUES
        (N'message.view'),(N'message.assign'),(N'review.level1'),(N'review.level2'),
        (N'review.level3'),(N'review.undo'),(N'audit.view'),(N'workflow.manage');

    INSERT INTO [orp].[Roles] ([Name]) VALUES (N'Reviewer'),(N'Operations manager');

    INSERT INTO [orp].[RolePermissions] ([RoleId],[PermissionId])
    SELECT r.[Id],p.[Id] FROM [orp].[Roles] r CROSS JOIN [orp].[Permissions] p
    WHERE r.[Name]=N'Operations manager'
        OR (r.[Name]=N'Reviewer'
            AND p.[Name] IN (N'message.view',N'message.assign',N'review.level1',
                N'review.level2',N'review.level3',N'review.undo',N'audit.view'));

    -- 3. Users and exact branch/department scopes.
    DECLARE @users TABLE ([UserName] nvarchar(80),[DisplayName] nvarchar(160),
        [RoleName] nvarchar(80),[IsAdmin] bit,[AllScopes] bit);
    -- Three broadly scoped reviewers support every workflow; Amelia demonstrates scoped access.
    INSERT INTO @users VALUES
        (N'amelia.hart',N'Amelia Hart',N'Reviewer',0,0),
        (N'theo.mercer',N'Theo Mercer',N'Reviewer',0,1),
        (N'priya.nair',N'Priya Nair',N'Reviewer',0,1),
        (N'lucas.bennett',N'Lucas Bennett',N'Reviewer',0,1),
        (N'admin',N'Administrator',N'Operations manager',1,1);

    INSERT INTO [orp].[Users] ([UserName],[DisplayName],[IsGlobalAdministrator])
    SELECT [UserName],[DisplayName],[IsAdmin] FROM @users;

    INSERT INTO [orp].[UserRoles] ([UserId],[BranchId],[DepartmentId],[RoleId])
    SELECT u.[Id],b.[Id],d.[Id],r.[Id] FROM @users v
    JOIN [orp].[Users] u ON u.[UserName]=v.[UserName]
    JOIN [orp].[Roles] r ON r.[Name]=v.[RoleName]
    CROSS JOIN [orp].[Branches] b
    CROSS JOIN [orp].[Departments] d
    WHERE v.[AllScopes]=1 OR (b.[Name]=N'London' AND d.[Name]=N'CS');

    -- 4. Workflow scenarios. Policy values correspond to the domain enums.
    DECLARE @Incoming int = 1, @Outgoing int = 2;
    DECLARE @UndoDisabled int = 0, @UndoLatestNonFinal int = 1, @UndoLatest int = 2;
    DECLARE @OriginalReviewer int = 0, @AnyAuthorizedUser int = 1;
    DECLARE @BlockActiveReview int = 0, @CancelActiveReview int = 1;
    DECLARE @workflows TABLE (
        [Ordinal] int PRIMARY KEY, [MessageType] nvarchar(20), [Name] nvarchar(100),
        [DepartmentName] nvarchar(80), [Levels] int, [Direction] int,
        [UndoApprovalMode] int, [UndoActorMode] int, [UndoActiveReviewMode] int
    );
    INSERT INTO @workflows VALUES
        (0,N'MT199',N'Single confirmation - no undo',N'CS',1,@Incoming,
            @UndoDisabled,@AnyAuthorizedUser,@BlockActiveReview),
        (1,N'MT299',N'Two confirmations - undo first',N'TFO',2,@Incoming,
            @UndoLatestNonFinal,@AnyAuthorizedUser,@CancelActiveReview),
        (2,N'MT671',N'Three reviews - owner undo',N'DC',3,@Incoming,
            @UndoLatest,@OriginalReviewer,@BlockActiveReview),
        (3,N'MT299',N'Outgoing confirmation - no undo',N'TFO',1,@Outgoing,
            @UndoDisabled,@AnyAuthorizedUser,@BlockActiveReview);
    INSERT INTO [orp].[WorkflowDefinitions]
        ([Name],[MessageType],[DepartmentId],[BranchId],[IsActive],[Direction],
         [UndoApprovalMode],[UndoActorMode],[UndoActiveReviewMode])
    SELECT v.[Name],v.[MessageType],d.[Id],NULL,1,v.[Direction],
        v.[UndoApprovalMode],v.[UndoActorMode],v.[UndoActiveReviewMode] FROM @workflows v
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName];
    INSERT INTO [orp].[WorkflowSteps] ([WorkflowDefinitionId],[Order],[ReviewLevel],[Required])
    SELECT w.[Id],level.[Value],level.[Value],1 FROM @workflows v
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName]
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=v.[MessageType] AND w.[Direction]=v.[Direction] AND w.[DepartmentId]=d.[Id]
    JOIN (VALUES (1),(2),(3)) level([Value]) ON level.[Value]<=v.[Levels];

    -- 5. Messages: preserve the first 75 Incoming examples, then add 25 Outgoing examples.
    -- TEST-00001 = single / London; TEST-00002 = two-step / Dublin;
    -- TEST-00003 = three-step / Singapore. TEST-00076 = Outgoing / TFO / London. Times cover the last 100 hours.
    DECLARE @now datetimeoffset = SYSUTCDATETIME();
    DECLARE @messageCount int = 100;
    ;WITH numbers AS (SELECT 1 AS n UNION ALL SELECT n+1 FROM numbers WHERE n<@messageCount)
    INSERT INTO [orp].[SwiftMessages]
        ([WarehouseId],[BodyContainsMx],[BodyContainsMt],[Body],[MessageType],[MessageTypeShort],
         [MessageLength],[MessageDate],[SenderRequestor],[ReceiverResponder],[Direction],
         [BranchId],[DepartmentId],[RoutingStatus],[LastSynchronizedAtUtc])
    SELECT CONCAT(N'TEST-',RIGHT(CONCAT(N'00000',n),5)),0,1,body.[Value],v.[MessageType],
        SUBSTRING(v.[MessageType],3,3),LEN(body.[Value]),DATEADD(hour,n-@messageCount,@now),
        N'TESTGB2LXXX',N'DEMOGB2LXXX',v.[Direction],b.[Id],d.[Id],N'Routed',@now
    FROM numbers
    JOIN @workflows v ON v.[Ordinal]=CASE WHEN n<=75 THEN (n-1)%3 ELSE 3 END
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName]
    JOIN [orp].[Branches] b ON b.[Name]=CASE (CASE WHEN n<=75 THEN (n-1)/3+v.[Ordinal] ELSE n-76 END)%3
        WHEN 0 THEN N'London' WHEN 1 THEN N'Dublin' ELSE N'Singapore' END
    CROSS APPLY (SELECT CONCAT(N'{1:F01TESTGB2LXXXX0000000000}{2:I',
        SUBSTRING(v.[MessageType],3,3),N'DEMOGB2LXXXXN}{4:',CHAR(10),N':20:TEST-',n,
        CHAR(10),N':79:SYNTHETIC TEST MESSAGE - ',v.[Name],CHAR(10),N'-}')) body([Value]);

    INSERT INTO [orp].[Messages] ([MessageId],[State],[CurrentAssigneeId],[WorkflowDefinitionId])
    SELECT s.[MessageId],N'New',NULL,w.[Id] FROM [orp].[SwiftMessages] s
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=s.[MessageType]
        AND w.[Direction]=s.[Direction] AND w.[DepartmentId]=s.[DepartmentId] AND w.[IsActive]=1 AND w.[BranchId] IS NULL;

    -- 6. Initial audit trail; later decisions are recorded by the application.
    INSERT INTO [orp].[AuditEvents]
        ([MessageId],[EventType],[UserId],[Timestamp],[OldState],[NewState],[DetailsJson],[CorrelationId],[ReviewId])
    SELECT [MessageId],N'MessageRegistered',NULL,@now,NULL,N'New',
        CONCAT(N'{"workflowDefinitionId":',[WorkflowDefinitionId],N'}'),N'sql-test-seed-v2',NULL
    FROM [orp].[Messages];

    COMMIT;
    PRINT 'Loaded 5 users, 4 demo workflows and 100 unassigned messages. Reviewer includes scoped review.undo.';

    -- 7. Readable summary for SSMS/sqlcmd. No generated IDs need to be copied into another script.
    SELECT w.[Name] AS [Workflow],v.[MessageType],v.[DepartmentName] AS [Department],
        CASE v.[Direction] WHEN @Incoming THEN N'Incoming' ELSE N'Outgoing' END AS [Direction],
        v.[Levels] AS [RequiredConfirmations],
        CASE v.[UndoApprovalMode] WHEN 0 THEN N'Disabled'
            WHEN 1 THEN N'Latest non-final approval' ELSE N'Latest approval, including final' END AS [Undo],
        CASE v.[UndoActorMode] WHEN 0 THEN N'Original reviewer' ELSE N'Any authorised reviewer' END AS [WhoCanUndo],
        CASE v.[UndoActiveReviewMode] WHEN 0 THEN N'Block undo' ELSE N'Cancel the active next review' END AS [DuringActiveReview]
    FROM @workflows v
    JOIN [orp].[Departments] d ON d.[Name]=v.[DepartmentName]
    JOIN [orp].[WorkflowDefinitions] w ON w.[MessageType]=v.[MessageType] AND w.[Direction]=v.[Direction] AND w.[DepartmentId]=d.[Id]
    ORDER BY v.[Ordinal];

    SELECT [UserName],[DisplayName],[RoleName] AS [Role],
        CASE WHEN [IsAdmin]=1 THEN N'Global administrator'
            WHEN [AllScopes]=1 THEN N'All 3 branches / all 3 departments'
            ELSE N'London / CS only' END AS [Access]
    FROM @users ORDER BY [IsAdmin],[UserName];
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK;
    THROW;
END CATCH;
