// <auto-generated />
//
// This file was generated from the backend OpenAPI contract.
// Do not edit this file manually.
//

export interface OrderDto {
  id: number;
  user: UserDto;
  items: OrderItemDto[];
  status: OrderStatus;
}

export interface OrderItemDto {
  productId: number;
  quantity: number;
  price: number;
}

export type OrderStatus =
  | "Created"
  | "Processing"
  | "Completed";

export interface PagedResultDto {
  items: OrderDto[];
  totalCount: number;
}

export interface UserDto {
  id: number;
  name: string;
  email?: string | null;
}
