using OpenApiTsContracts.OpenApi;

namespace OpenApiTsContracts.Generation;

public sealed class TypeScriptGenerator(string? namespacePrefix = null)
{
    public string Generate(OpenApiContractDocument document)
    {
        var names = new SchemaNameMap(document, namespacePrefix);
        var resolver = new TypeScriptTypeResolver(names);
        var writer = new TypeScriptWriter();

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("//");
        writer.WriteLine("// This file was generated from the backend OpenAPI contract.");
        writer.WriteLine("// Do not edit this file manually.");
        writer.WriteLine("//");
        writer.WriteLine();

        foreach (var (sourceName, outputName) in names.Entries.OrderBy(
                     entry => entry.OutputName,
                     StringComparer.Ordinal))
        {
            var schema = document.Schemas[sourceName];
            if (schema.EnumValues is not null)
            {
                WriteNamedEnum(writer, outputName, schema);
            }
            else if (schema.Kind == OpenApiSchemaKind.Object && !schema.IsNullable)
            {
                WriteInterface(writer, resolver, outputName, schema);
            }
            else
            {
                writer.WriteLine($"export type {outputName} = {resolver.Resolve(schema)};");
            }

            writer.WriteLine();
        }

        return writer.ToString();
    }

    private static void WriteNamedEnum(
        TypeScriptWriter writer,
        string name,
        OpenApiSchema schema)
    {
        var enumValues = schema.EnumValues!;
        var values = enumValues.Select(value => value.TypeScriptText).ToList();
        if (schema.IsNullable &&
            enumValues.All(value => value.Kind != OpenApiLiteralKind.Null))
        {
            values.Add("null");
        }

        writer.WriteLine($"export type {name} =");
        if (values.Count == 1)
        {
            writer.WriteLine($"  {values[0]};");
            return;
        }

        for (var index = 0; index < values.Count; index++)
        {
            var terminator = index == values.Count - 1 ? ";" : string.Empty;
            writer.WriteLine($"  | {values[index]}{terminator}");
        }
    }

    private static void WriteInterface(
        TypeScriptWriter writer,
        TypeScriptTypeResolver resolver,
        string name,
        OpenApiSchema schema)
    {
        writer.WriteLine($"export interface {name} {{");
        foreach (var property in schema.ObjectProperties)
        {
            var optional = property.IsRequired ? string.Empty : "?";
            writer.WriteLine(
                $"  {TypeScriptNames.PropertyName(property.Name)}{optional}: " +
                $"{resolver.Resolve(property.Schema, 1)};");
        }

        writer.WriteLine("}");
    }
}
